### ISSUE TITLE
Showing offline or Invalid domain even if it is online and valid after using the prober.

### ISSUE THREAD

**Issue by sumanbasuli** [TxSadhu/DomFu#5]
Showing offline or Invalid domain even if it is online and valid after using the prober. And also shows no result on the first time running probe on some domains but not all.

**Comment by sumanbasuli** [comment]
[**Temporary Fix:**]

**For Unix based systems:**
- replace `nameserver NS_IP` in _/etc/resolv.conf_ with `nameserver 1.1.1.1`

**For Windows:** 

- Control Panel > 
    - Network and Internet > Network and Sharing center > Change adapter settings (Left sidebar) >
    - Select your network (Right click) > Properties >
    - select Internet protocol version 4 (TCP/IPv4) > Properties >
    - use the following DNS  server address > Preffered DNS server - 1.1.1.1 and Alternative DNS server - 1.0.0.1 > OK

**Comment by TxSadhu** [comment]
**For Windows:** 

- Control Panel > 
    - Network and Internet > Network and Sharing center > Change adapter settings (Left sidebar) >
    - Select your network (Right click) > Properties >
    - select Internet protocol version 4 (TCP/IPv4) > Properties >
    - use the following DNS  server address > Preffered DNS server - 1.1.1.1 and Alternative DNS server - 1.0.0.1 > OK
